name: Check formatting of LIPMWalking sources

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format-10
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install clang-format-10
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
